### ISSUE TITLE
Cloudflare better

### ISSUE THREAD

**Issue by Pmaru-top** [SweetRiceMC/ResourcePack#1]
你现在使用的 `ghproxy.com` 反向代理在中国的连接质量很糟糕

![Screenshot from 2024-02-17 22-40-05](https://github.com/SweetRiceMC/ResourcePack/assets/78346594/deaf4cb6-bc2f-46f4-91d4-0505174ea560)

所以我建议你使用`Cloudflare pages`进行分发

![Screenshot from 2024-02-17 22-40-17](https://github.com/SweetRiceMC/ResourcePack/assets/78346594/b91b2fd9-f25f-42dc-86c9-80ad283e81fd)

你还可以联系我（you know me）免费分发你的文件而且非常好连接质量
![Screenshot from 2024-02-17 22-47-18](https://github.com/SweetRiceMC/ResourcePack/assets/78346594/09922549-5971-40ab-b4d2-b328bb3c52b7)

**Comment by MrXiaoM** [comment]
Pages 有单文件 26M 大小限制。现我已将资源部署到比免费镜像源更稳定的地方。
